services:
    postgres:
        image: bitnami/postgresql:latest
        ports:
            - "5433:5432"
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        volumes:
            - prisma_pg_data:/bitnami/postgresql
volumes:
    prisma_pg_data:
